<?php /** @var \Challenge\ServiceWorker\Block\Register $block */ ?>
<?php if ($block->isEnabled()): ?>
    <script type="text/javascript">
        (() => {
            // ServiceWorker is a progressive technology. Ignore unsupported browsers
            if ('serviceWorker' in navigator)
            {
                console.log('Service Worker registration in progress.');
                navigator.serviceWorker.
                register('<?php echo $block->getServiceWorkerJsUrl() ?>').
                then(function() {
                    console.log('Service Worker registration complete.');
                }, function() {
                    console.log('Service Worker registration failure.');
                });
            } else {
                console.log('Service Worker is not supported.');
            }
        })();
    </script>
<?php endif; ?>
